services:
  db:
    image: postgres:17.0
    container_name: mj_database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    container_name: mj_app
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env.local
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./api:/rails
    ports:
      - 3001:3001
    depends_on:
      - redis
      - db

  sidekiq:
    container_name: mj_sidekiq
    build:
      context: ./api
      dockerfile: Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      REDIS_URL: redis://redis:6379
    env_file:
      - ./api/.env.local
    volumes:
      - ./api:/rails
    depends_on:
      - app
      - redis

  redis:
    container_name: mj_redis
    image: redis:7.0
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    depends_on:
      - db


volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
